server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: test-task

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: username
    password:

  h2:
    console:
      enabled: false

  elasticsearch:
    uris: http://elasticsearch:9200

camunda:
  bpm:
    admin-user:
      id: username
      password: password
      first-name: Test
      last-name: User
    database:
      type: h2
    job-execution:
      enabled: false

scoring-variables:
  dmn-key: "scoring-decision"
  is-ip-key: "isIp"
  is-resident-key: "isResident"
  region-key: "region"
  capital-key: "capital"
  isRejected-key: "isRejected"
  reason-key: "reason"
  non-resident-prefix: "9909"
  ip-inn-length: 12